services:
  service-1:
    container_name: service-1
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_IP: ${DB_IP:-db}
    depends_on:
      - db
      - service-2
  service-2:
    container_name: service-2
    image: alihmzyv/docker-compose-study-service-2:2.0
    restart: always
    ports:
      - "8081:8081"
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: compose_db
      POSTGRES_USER: ${DB_USER:-db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    volumes:
      - database-data:/var/lib/postgresql/data/

  reverse_proxy:
    restart: always
    image: nginx:latest
    hostname: proxy
    container_name: reverse_proxy
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service-1
      - service-2
volumes:
  database-data: